### ISSUE TITLE
Please update PyPi asap (0.10.2 and latest (0.11.x at time of writing))

### ISSUE THREAD

**Issue by CoMPaTech** [laetificat/haanna#16]
Hi @laetificat,

As requested earlier in the PRs (#13 & #14), but please update PyPi. I've merged the PRs now to keep things going, but we really do need you to update PyPi.

 If you have less time available I'd suggest you add @bouwew as author and at least myself to PyPi to be able to update (sam username). Otherwise, just indicate and we'll unfortunately have to create another module on PyPi.

Kind regards,

Tom

**Comment by bouwew** [comment]
Hi Tom,

Please change the version to 0.11.0 instead of 0.11.9.

I ended up at 0.11.9 due to my way of testing each update individually. No
need to copy this version-number along with the official update.

Mvg, Bouwe

**Comment by CoMPaTech** [comment]
> Hi Tom, Please change the version to 0.11.0 instead of 0.11.9. I ended up at 0.11.9 due to my way of testing each update individually. No need to copy this version-number along with the official update. Mvg, Bouwe
> […](#)

Done - it also was at 0.10.2 due to the different merges, but it's 11.0 now

**Comment by bouwew** [comment]
Thanks! I quickly loaded the 0.11.0 version via my plugwise-dev custom_component, all working as far as I can see/test.

**Comment by CoMPaTech** [comment]
Cool!
Waiting for @laetificat than!

**Comment by laetificat** [comment]
Hello @CoMPaTech, Unfortunately I'm not able to update the PyPi repo right now. I will update it this evening and at the same time add you and @bouwew as authors.

**Comment by CoMPaTech** [comment]
Tnx!

**Comment by laetificat** [comment]
I have updated PyPi and this repository to include release 0.11.0, I also added @CoMPaTech as a maintainer for the PyPi repo.

@bouwew You can give me your PyPi username if you want to be a maintainer too.
