### ISSUE TITLE
HA interface not not showing the selected preset state

### ISSUE THREAD

**Issue by Mariusthvdb** [laetificat/haanna#29]
following a discussion on https://community.home-assistant.io/t/advice-how-to-load-sensor-info-from-plugwise-anna-thermostat-web-interface-xml/87801/132?u=mariusthvdb please let me create this issue for the HA interface not showing the selected preset state.

Not sure how to post more than in the dicsussion, but bottom line is the HA app can endup in a manual override situation (as described in the community post) while the thermostat in fact is in a automode (preset configuration), set in the App.

HA doesn't follow that change, and stays is manual override

Only way to have that reflected again in the HA interface then is 3 fold: click the flame (to yet again set to manual mode), click the calendar icon (to have it enter sleep ode in my setting) and then again click calendar, to finally arrive in the auto mode.....

If both HA and the Anna app command the thermostat in that situation, it is mixing signals which can't be good...

let me know if you need more to investigate/debug

I use the native integration in HA 102.2

__update__
maybe it is a bug in the Anna app..... selecting a preset after a manual override on the app,doesnt show on the Anna thermostat itself either. One needs to click 2 or 3 times before it is displayed.

seems only touching the top of the thermostat works as is supposed to?
please let me know if you see this too.

**Comment by bouwew** [comment]
A similar issue? https://github.com/laetificat/anna-ha/issues/29

**Comment by bouwew** [comment]
Please see my feedback in #29. Setting a preset that was active before does not seem work from with HA. I also tried to do this from the Plugwise app: same result.
My conclusion: a bug in the Anna app.

**Comment by bouwew** [comment]
I suggest we close this issue as there is nothing we can do this fix this.

**Comment by CoMPaTech** [comment]
@Mariusthvdb we've just released 0.2.0 of our custom_component (with an upstream HA-PR in progress). As per the release of HA-core 0.109 this wednesday (or if you already run HA-core beta 109) you can start using plugwise-beta.

Closing this issue. If you have any further comments or issues feel free to update

The (community post)[https://community.home-assistant.io/t/plugwise-smile-custom-component-beta/183560/3?u=compatech]
The (module)[https://github.com/plugwise/Plugwise-Smile] replacing this repository
The (custom_component)[https://github.com/plugwise/plugwise-beta]
