### ISSUE TITLE
Release 0.10.0 time errors on python 3.6

### ISSUE THREAD

**Issue by CoMPaTech** [laetificat/haanna#9]
Creating commit to solve this (as 0.10.1) for merging and distributing to PyPi

**Comment by CoMPaTech** [comment]
@laetificat can you please review and update on PyPi?

**Comment by laetificat** [comment]
It has been merged and released to PyPi.

**Comment by CoMPaTech** [comment]
Tnx!

**Comment by CoMPaTech** [comment]
Updated in the HA repo as https://github.com/home-assistant/home-assistant/pull/25693
